name: settings
label: Setting
icon: custom
hidden: true
fields:
  type:
    label: Type
    type: text
    allowedValues:
      - user
      - space
      - cloud
  object_name:
    label: Object
    type: text
    index: true
  record_id:
    label: Record ID
    type: text
    index: true
  settings:
    label: Settings
    type: object
    blackbox: true
permission_set:
  user:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: false
  admin:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: true
    viewAllRecords: true
